FROM node:12-alpine
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait wait
RUN chmod +x /wait
WORKDIR /home/nodejs/app
ENV NODE_ENV production
COPY package*.json ./
RUN npm install
ARG port=80
COPY . ./
CMD /wait && NODE_ENV=production node app.js 
