version: 3
services:
  backend-test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
      args:
        port: ${PORT}
      env_file: 
        - ../.env
      restart: always
      ports:
        = "${PORT}:${PORT}"
      environment: 
        WAIT_HOSTS: database-test:27017
  database-test:
    image: mongo:4.0
    env_file: 
      - ../.env
    volumes:
      - ".${MONGO_TEST_DATA_DIR}:${MONGO_TEST_DATA_DIR}"
    expose:
      - 27107
    command: "mongod --smallfiles logpath=${MONGO_LOG_FILE}"
